# Generated by Django 5.2.16 on 2026-08-31 11:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orders_orde_status_883c98_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='awb_code',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='courier_service',
            field=models.CharField(blank=True, help_text='Courier service selected by shipping provider.', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='manifest_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_token',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_label_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_order_id',
            field=models.CharField(blank=True, db_index=True, help_text='Order ID returned by shipping provider.', max_length=150),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_response',
            field=models.JSONField(blank=True, default=dict, help_text='Latest response received from shipping provider.'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_response',
            field=models.JSONField(blank=True, default=dict, help_text='Latest tracking response received from courier/shipping provider.'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_status', 'placed_at'], name='orders_orde_shippin_e4da21_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['awb_code'], name='orders_orde_awb_cod_3319a5_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipment_id'], name='orders_orde_shipmen_7d8c70_idx'),
        ),
    ]
