# Generated by Django 5.2.16 on 2026-09-02 14:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_order_orders_orde_shipmen_7d8c70_idx_and_more'),
        ('products', '0003_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(blank=True, db_index=True, max_length=150),
        ),
        migrations.AddField(
            model_name='payment',
            name='refund_response',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='payment',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('packed', 'Packed'), ('shipped', 'Shipped'), ('in_transit', 'In Transit'), ('out_for_delivery', 'Out For Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('return_requested', 'Return Requested'), ('exchange_requested', 'Exchange Requested'), ('return_approved', 'Return Approved'), ('exchange_approved', 'Exchange Approved'), ('return_in_transit', 'Return In Transit'), ('returned', 'Returned'), ('exchanged', 'Exchanged'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('authorized', 'Authorized'), ('captured', 'Captured'), ('failed', 'Failed'), ('partially_refunded', 'Partially Refunded'), ('refunded', 'Refunded')], db_index=True, default='created', max_length=30),
        ),
        migrations.CreateModel(
            name='ReturnRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(db_index=True, editable=False, max_length=40, unique=True)),
                ('request_type', models.CharField(choices=[('return', 'Return'), ('exchange', 'Exchange')], db_index=True, default='return', max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pickup_scheduled', 'Pickup Scheduled'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('received', 'Received'), ('inspection_pending', 'Inspection Pending'), ('inspection_completed', 'Inspection Completed'), ('refund_pending', 'Refund Pending'), ('refunded', 'Refunded'), ('exchange_pending', 'Exchange Pending'), ('exchange_shipped', 'Exchange Shipped'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=30)),
                ('reason', models.CharField(choices=[('wrong_size', 'Wrong Size'), ('wrong_product', 'Wrong Product'), ('damaged', 'Damaged Product'), ('defective', 'Defective Product'), ('quality_issue', 'Quality Issue'), ('not_as_expected', 'Not As Expected'), ('colour_issue', 'Colour Issue'), ('fit_issue', 'Fit Issue'), ('changed_mind', 'Changed Mind'), ('other', 'Other')], default='other', max_length=50)),
                ('reason_details', models.TextField(blank=True)),
                ('customer_note', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('courier_name', models.CharField(blank=True, max_length=150)),
                ('courier_service', models.CharField(blank=True, max_length=150)),
                ('courier_company_id', models.CharField(blank=True, max_length=100)),
                ('awb_code', models.CharField(blank=True, db_index=True, max_length=150)),
                ('tracking_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('tracking_url', models.URLField(blank=True, max_length=1000)),
                ('pickup_scheduled', models.BooleanField(default=False)),
                ('pickup_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('shiprocket_order_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('shiprocket_shipment_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('shipping_status', models.CharField(blank=True, max_length=100)),
                ('shipping_response', models.JSONField(blank=True, default=dict)),
                ('tracking_response', models.JSONField(blank=True, default=dict)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('refund_id', models.CharField(blank=True, db_index=True, max_length=150)),
                ('refund_status', models.CharField(blank=True, max_length=50)),
                ('refund_response', models.JSONField(blank=True, default=dict)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='return_requests', to='orders.order')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_return_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Return / Exchange Request',
                'verbose_name_plural': 'Return / Exchange Requests',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('replacement_color', models.CharField(blank=True, max_length=100)),
                ('replacement_size', models.CharField(blank=True, max_length=50)),
                ('inspection_status', models.CharField(blank=True, max_length=50)),
                ('inspection_note', models.TextField(blank=True)),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='orders.orderitem')),
                ('replacement_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replacement_return_items', to='products.productvariant')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.returnrequest')),
            ],
            options={
                'verbose_name': 'Return / Exchange Item',
                'verbose_name_plural': 'Return / Exchange Items',
                'ordering': ('id',),
            },
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['order', 'status'], name='orders_retu_order_i_62acda_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['request_type', 'status'], name='orders_retu_request_89c95f_idx'),
        ),
        migrations.AddIndex(
            model_name='returnrequest',
            index=models.Index(fields=['user', 'created_at'], name='orders_retu_user_id_41b529_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_request'], name='orders_retu_return__06a3d7_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['order_item'], name='orders_retu_order_i_b255fe_idx'),
        ),
    ]
