# Generated by Django 5.2.16 on 2026-08-14 15:40

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0002_alter_brand_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['product', 'color', 'size']},
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('5.00'))]),
        ),
        migrations.AddIndex(
            model_name='brand',
            index=models.Index(fields=['is_active', 'name'], name='products_brand_active_name_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_active', '-created_at'], name='products_active_created_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['department', 'is_active'], name='products_dept_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_active'], name='products_cat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['subcategory', 'is_active'], name='products_subcat_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_featured', 'is_active'], name='products_featured_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_best_seller', 'is_active'], name='products_bestseller_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_trending', 'is_active'], name='products_trending_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_new_arrival', 'is_active'], name='products_new_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_offer', 'is_active'], name='products_offer_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_clearance_sale', 'is_active'], name='products_clearance_active_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product', 'order'], name='product_image_order_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'is_active', 'stock'], name='product_variant_stock_idx'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='unique_product_color_size'),
        ),
    ]
