# Generated by Django 5.2.16 on 2026-08-06 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0004_order_orders_orde_status_883c98_idx_and_more'),
        ('products', '0002_alter_brand_options_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventorySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('allow_negative_stock', models.BooleanField(default=False)),
                ('auto_restore_on_cancel', models.BooleanField(default=True)),
                ('auto_restore_on_return', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Inventory Setting',
                'verbose_name_plural': 'Inventory Settings',
            },
        ),
        migrations.CreateModel(
            name='LowStockAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=5)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='low_stock_alert', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Low Stock Alert',
                'verbose_name_plural': 'Low Stock Alerts',
                'ordering': ('-is_active', 'current_stock'),
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase / Stock In'), ('sale', 'Sale / Stock Out'), ('order_cancelled', 'Order Cancelled / Stock Restore'), ('return', 'Customer Return / Stock Restore'), ('refund', 'Refund / Stock Restore'), ('manual_increase', 'Manual Stock Increase'), ('manual_decrease', 'Manual Stock Decrease'), ('damaged', 'Damaged Stock'), ('correction', 'Stock Correction')], db_index=True, max_length=30)),
                ('quantity_change', models.IntegerField(help_text='Positive value increases stock; negative value decreases stock.')),
                ('stock_before', models.PositiveIntegerField()),
                ('stock_after', models.PositiveIntegerField()),
                ('reference', models.CharField(blank=True, db_index=True, max_length=150)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_transactions', to='products.productvariant')),
            ],
            options={
                'verbose_name': 'Inventory Transaction',
                'verbose_name_plural': 'Inventory Transactions',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['variant', 'created_at'], name='inventory_i_variant_6e8bad_idx'), models.Index(fields=['transaction_type', 'created_at'], name='inventory_i_transac_1f1168_idx'), models.Index(fields=['order', 'created_at'], name='inventory_i_order_i_ff6ca3_idx')],
            },
        ),
    ]
