# Generated by Django 5.2.16 on 2026-08-06 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('orders', '0004_order_orders_orde_status_883c98_idx_and_more'),
        ('products', '0002_alter_brand_options_alter_productimage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorysettings',
            name='auto_restore_on_refund',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='stock_after',
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AddIndex(
            model_name='inventorytransaction',
            index=models.Index(fields=['product', 'created_at'], name='inventory_i_product_2e3433_idx'),
        ),
        migrations.AddIndex(
            model_name='lowstockalert',
            index=models.Index(fields=['is_active', 'current_stock'], name='inventory_l_is_acti_ce8f40_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventorytransaction',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_change', 0), _negated=True), name='inventory_quantity_change_nonzero'),
        ),
    ]
