# Generated by Django 5.2.16 on 2026-09-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_inventorysettings_auto_restore_on_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase / Stock In'), ('sale', 'Sale / Stock Out'), ('order_cancelled', 'Order Cancelled / Stock Restore'), ('return', 'Customer Return / Stock Restore'), ('refund', 'Refund / Stock Restore'), ('exchange_return', 'Exchange Return / Stock Restore'), ('exchange_out', 'Exchange Replacement / Stock Out'), ('manual_increase', 'Manual Stock Increase'), ('manual_decrease', 'Manual Stock Decrease'), ('damaged', 'Damaged Stock'), ('correction', 'Stock Correction')], db_index=True, max_length=30),
        ),
    ]
