# Generated by Django 5.2.16 on 2026-08-05 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_orders_orde_status_883c98_idx_and_more'),
        ('products', '0002_alter_brand_options_alter_productimage_options_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewhelpful',
            options={'ordering': ('-created_at',), 'verbose_name': 'Review Helpful Vote', 'verbose_name_plural': 'Review Helpful Votes'},
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_product_0aaa55_idx',
        ),
        migrations.RemoveIndex(
            model_name='review',
            name='reviews_rev_user_id_35ef9b_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='review_rating_idx',
            old_name='reviews_rev_rating_2db6dd_idx',
        ),
        migrations.AlterField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'status', '-created_at'], name='review_product_status_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='review_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['is_verified_purchase', 'status'], name='review_verified_status_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['review', '-created_at'], name='review_helpful_review_idx'),
        ),
        migrations.AddIndex(
            model_name='reviewhelpful',
            index=models.Index(fields=['user', '-created_at'], name='review_helpful_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__gte', 1), ('rating__lte', 5)), name='review_rating_between_1_and_5'),
        ),
    ]
